# Per-host composition for ac-box.
#
# Two things live here rather than in a platform module, both for real reasons:
#
#   1. The hardware import. Nix's module system cannot make `imports` depend on
#      `config`, so driving this from homelab.host.name is infinite recursion,
#      not a style choice. It is therefore resolved with a literal path here.
#   2. Wiring tenant options to host facts. Tenant modules declare and never
#      reach, so something has to hand arcade-hub the LAN address -- and that
#      something is the host composition, which is the one place allowed to know
#      both sides.
{ config, lib, ... }:

let
  # hardware-configuration.nix is machine-local and gitignored by design: it is
  # generated by nixos-generate-config and carries this box's actual disks. Only
  # the .example stub is tracked, and the stub says of itself that it will not
  # boot a real machine -- so falling back to it is a loud failure, not a quiet
  # one. Fetch the real file read-only from the box; never invent one.
  hardwarePath =
    if builtins.pathExists ./hardware-configuration.nix then
      ./hardware-configuration.nix
    else
      ./hardware-configuration.nix.example;
in
{
  imports = [ hardwarePath ];

  # ---------------------------------------------------------------------------
  # Phase 1: enforcement fully off.
  #
  # The contract's assertions still run -- port collisions, the memory budget,
  # forwarded-without-justification, mgmt-without-address all fail evaluation
  # right now. Only the derivations are gated, so this configuration contributes
  # no slices, no firewall rules, no scrape configs and no /etc/homelab files.
  # That is what makes the first switch provably a no-op.
  #
  # Each flag is flipped in its own later step, smallest blast radius first:
  # inventory, then firewall, then scrape, then slices. Set explicitly rather
  # than relying on the defaults, so the phase is legible in the config itself.
  # ---------------------------------------------------------------------------
  # mkDefault, not a bare false. Setting these at normal priority made every
  # phase flip untestable: `extendModules` with `inventory = true` failed with
  # "conflicting definition values" against this file, so proving a phase's
  # blast radius required editing the repo first. With mkDefault, a variant can
  # override cleanly and each flip can be dry-activated before it is committed.
  homelab.enforce = {
    # Phase 4. Derives interface-scoped rules from the port registry. Verified
    # additive: dry-activate adds only a firewall.service RELOAD, and the
    # generated ruleset is a correct superset of what is live -- AC's forwarded
    # 8081-8096, 8181-8196 and 9600-9615 all present on enp8s0, arcade's ports
    # intact, and 11200 correctly getting no rule at all because it is declared
    # scope = "local". ac-host's global openings still exist alongside these;
    # removing them is the separate step where the exposure actually shrinks.
    firewall = lib.mkDefault true;

    # Phase 3. Writes /etc/homelab/tenants.json for boxctl. Touches no units --
    # its activation plan came out byte-identical to phase 1's.
    inventory = lib.mkDefault true;

    # Phase 5. Generates prometheus scrapeConfigs from tenant declarations,
    # reproducing the existing five job names byte-for-byte, because renaming a
    # job orphans every dashboard built on it.
    scrape = lib.mkDefault true;

    # Phase 6. The only flag with real service churn, deliberately taken in its
    # own switch rather than riding along with the three quiet ones.
    #
    # Safe now because resources.nix assigns Slice= only where tier != critical
    # AND quiet.drainable. Slice= applies at unit start, so assigning it bounces
    # the unit -- and bouncing ac-host-static means `docker rm -f` on three live
    # race servers. assetto is therefore never sliced, which costs nothing: the
    # guarantee comes from AllowedCPUs fencing background and batch away from
    # the cores races use, not from confining races.
    slices = lib.mkDefault true;
  };

  # ---------------------------------------------------------------------------
  # CI stack (Buildkite agent + MinIO), adopted under systemd (beads
  # homelab-bqo.12). Was hand-started via `docker compose up -d --build`, per
  # the compose file's own header -- no lifecycle management, no start-on-boot,
  # no supervised restart. Not a resource-fencing fix (that's already handled
  # by the compose file's own cgroup_parent, see homelab-bqo.27): this is
  # purely about the stack surviving a reboot without a human remembering to
  # run docker compose by hand.
  #
  # THIS FLAG MUST NOT REACH THE BOX BEFORE THE HAND-STARTED STACK IS STOPPED.
  # docker-compose up -d --build against the same project name as an
  # already-running stack is a port/network collision, not a clean takeover --
  # see modules/ci/default.nix's own HAZARD 1. The runbook sequences this:
  # commit and push this line, but do not switch until the box-side stop +
  # volume/port verification (module header, steps 1-4) is done.
  homelab.ci.enable = true;

  # modules/ci/default.nix deliberately leaves wantedBy unset -- "a decision
  # for whoever wires this module in" -- because the whole point of this bead
  # is starting on boot instead of a human remembering docker compose up -d.
  systemd.services.ac-host-ci.wantedBy = [ "multi-user.target" ];

  # ---------------------------------------------------------------------------
  # Tenants, reproducing ac-box's live configuration exactly.
  # ---------------------------------------------------------------------------

  services.ac-host = {
    enable = true;
    repoDir = "/var/lib/ac-host/src";
    stateDir = "/var/lib/ac-host";
    authOpen = false;
    requiredRole = "ac-practice";
  };

  services.ac-host-dev = {
    enable = true;
    stateDir = "/var/lib/ac-host-dev";
  };

  # The canonical arcade-hub module deliberately has no defaults for lanAddress
  # or gameInterface: they were duplicated into two tenant modules and drifted.
  # They are host facts, so they come from homelab.host and are passed in here.
  services.arcade-hub = {
    enable = true;
    lanAddress = config.homelab.host.networks.lan.address;
    gameInterface = config.homelab.host.networks.lan.interface;
    rsync.enable = true;
    freeciv.enable = true;
    mindustry.enable = true;
  };

  # ---------------------------------------------------------------------------
  # agent-hub: the local coding-agent model server (tenant declared in
  # tenants.nix, module imported from the agent-hub flake input).
  #
  # Phase 1 only -- serving, no repo access. runner.enable is deliberately
  # left false: it needs a sops-backed githubTokenFile (beads homelab-bqo.10,
  # still open) and the runner image loaded into this box's Docker, neither of
  # which is done. Turning llm on does not turn runner on; they are separate
  # flags for exactly this reason.
  #
  # lanAddress/gameInterface come from homelab.host rather than the module's
  # own defaults, same as services.arcade-hub above. The module happens to
  # default to this box's values today, which is precisely the drift trap the
  # arcade-hub comment describes -- host facts are read from the host, never
  # inherited from a tenant's guess.
  services.agent-hub = {
    enable = true;
    lanAddress = config.homelab.host.networks.lan.address;
    gameInterface = config.homelab.host.networks.lan.interface;

    llm = {
      enable = true;

      # Qwen3-Coder-Next, 80B total / 3B active MoE (512 experts, 10 routed
      # per token), Q8_0, ~85 GB across four shards. Point llama.cpp at shard
      # 1; it finds the rest in the same directory.
      #
      # Chosen over the bigger Qwen3-Coder-480B-A35B deliberately, and the
      # reasoning is worth keeping because it inverts the obvious answer:
      #
      #   - The 480B does not fit here at a quantization that preserves code
      #     quality. Q4_K_S is 273 GB against 251 GiB of physical RAM, so it
      #     is not a tuning question -- it does not fit at all. What fits is
      #     Q2_K_XL (180 GB) or Q3_K_S (207 GB), and sub-Q4 quantization
      #     damage lands hardest on exactly this workload.
      #   - Qwen's own line on the 80B-A3B variant is that it retains ~96% of
      #     the 480B flagship's quality. Trading ~4% of a full-precision model
      #     against Q2/Q3 damage to a larger one is not a close call.
      #   - Q8_0 is effectively lossless, so the number above is the quality
      #     we actually get rather than a starting point to degrade from.
      #   - CPU token rate tracks ACTIVE parameters, not total. 3B active vs
      #     35B active is roughly a tenfold difference in memory traffic per
      #     token on a box with no GPU and ~130 GB/s of DDR4 -- the difference
      #     between a tool you use and one you wait on.
      #
      # If this turns out to be wrong, the 480B UD-Q2_K_XL is a modelPath
      # change plus a memoryShare bump, and both can be A/B'd on this box.
      #
      # A quoted STRING, not a Nix path literal. The option's type is
      # types.path, which accepts either -- but an unquoted ./path literal
      # would make Nix copy the whole GGUF into /nix/store at eval time.
      # At a hundred-plus gigabytes that is not a mistake you notice early.
      modelPath = "/srv/agent-hub/models/Qwen3-Coder-Next-Q8_0-00001-of-00004.gguf";

      # PHYSICAL cores inside background.slice's fence, not logical threads
      # and not the host's 56. The fence (resources.nix) gives background
      # cores 3-25 plus their SMT siblings; llama.cpp's generation threads
      # want one per physical core -- oversubscribing to the siblings makes
      # a memory-bandwidth-bound workload slower, not faster.
      #
      # This is the option's own documented contract: "must be set to match
      # the CPU allowance the platform's tenant tier actually grants this
      # service". If the tier shares below move, this moves with them.
      threads = 23;

      # Not larger, even though the model natively supports 262144 and
      # background.slice's ceiling would hold the KV cache for it. The binding
      # constraint on CPU is PREFILL, not RAM: prompt processing is
      # compute-bound, this is Broadwell (no AVX-512), and ingesting a
      # six-figure-token prompt would take longer than the answer is worth.
      # Raise it once a measured prefill rate says it is affordable.
      contextSize = 32768;

      extraArgs = [
        # THE flag on this box. Two NUMA nodes (dual E5-2680 v4); without
        # it llama.cpp allocates on whichever node loaded the model and the
        # other socket's threads pay remote-memory latency on every token.
        "--numa" "distribute"

        # Prompt processing is compute-bound rather than bandwidth-bound, so
        # unlike --threads it does benefit from the SMT siblings: 23 physical
        # cores x 2 threads inside the fence.
        "--threads-batch" "46"

        # Swap is 0 on this box, so an evicted model page is a disk re-read
        # in the middle of a token. Pinning is safe here only because
        # background.slice's MemoryMax (0.65 * 251 GiB ~= 163 GiB) is far
        # above the model + KV cache -- mlock'd pages cannot be reclaimed,
        # so a model sized near the ceiling turns a slowdown into an OOM
        # kill. Needs LimitMEMLOCK below; systemd's default is 8 MiB.
        "--mlock"

        "--flash-attn" "on"

        # Serves /metrics on the same port. Not yet scraped -- see the
        # agent-hub tenant's `metrics = null` in tenants.nix for why
        # (metrics.nix scrapes 127.0.0.1 and this binds the LAN address).
        "--metrics"
      ];
    };
  };

  # --mlock is a no-op-with-a-warning without this: systemd's default
  # LimitMEMLOCK is 8 MiB, and llama.cpp will fail to pin a 100+ GiB model
  # against it. Set here rather than in the agent-hub module because it is a
  # consequence of THIS host's extraArgs choice, not a property of the module.
  # Merges with the module's own serviceConfig -- different keys, no conflict.
  systemd.services.agent-hub-llm.serviceConfig.LimitMEMLOCK = "infinity";

  # ---------------------------------------------------------------------------
  # Tier shares, rebalanced to point this machine at the model server.
  #
  # The defaults in modules/tenant/resources.nix (critical 0.35/0.50,
  # interactive 0.15/0.20, background 0.30/0.25, batch 0.10/0.05) were written
  # before ac-box had an LLM tenant, and they cap agent-hub at 75 GiB of a
  # 251 GiB machine. Measured on the box 8 Sep 2026 before changing anything:
  # 4 GiB of 251 in use, load average 0.00, and all thirteen containers
  # together at 275 MiB. There is nothing to reclaim from the other tenants --
  # the tier table was the only thing standing between the LLM and the box.
  #
  # Every value here is an override of a mkDefault in resources.nix, so no
  # mkForce is needed and the defaults stay intact for any other host.
  #
  # memoryShare must sum to <= 0.9 (resources.nix's budget assertion, which
  # runs whether or not enforce.slices is on). These sum to exactly 0.90.
  #
  # Two consequences worth stating out loud rather than discovering later:
  #
  #   1. assetto is never assigned a slice at all (tier = critical AND
  #      quiet.drainable = false), so its processes and containers run in
  #      system.slice, whose CPUWeight is unset -- i.e. 100. Giving background
  #      a CPUWeight of 700 therefore ranks the model server ABOVE the race
  #      servers under contention, not merely above the other tiers. That is
  #      the deliberate choice being made here. What protects racing is the
  #      fence, not the weight: cores 0-2 (plus siblings 28-30) are outside
  #      background's and batch's AllowedCPUs entirely, so system.slice has
  #      exclusive use of them no matter what the LLM is doing.
  #
  #   2. critical.cpuShare is not about how much CPU assetto gets -- its slice
  #      is empty. It is the input to reservedForCritical, i.e. how many
  #      physical cores the fence keeps for everything unsliced. Lowering it
  #      to 0.10 is what hands the model server the other 23 cores.
  homelab.tiers = {
    critical = {
      memoryShare = 0.10; # 25.1 GiB. Measured usage of the whole racing stack: well under 1 GiB.
      cpuShare = 0.10; # -> 3 physical cores (0-2) reserved outside the fence.
    };
    interactive = {
      memoryShare = 0.05; # 12.5 GiB for arcade + observability; Grafana+Prometheus measured at ~0.4 GiB.
      cpuShare = 0.05;
    };
    background = {
      # ~163 GiB for the model + KV cache. Sized from the model that is
      # actually deployed (Qwen3-Coder-Next Q8_0, ~79 GiB) with room for a
      # much larger one, rather than from "give it everything": memoryShare is
      # a CEILING, not a reservation, so an oversized one costs nothing at
      # runtime -- but it does consume the 0.9 budget, and the tier it was
      # taking that budget from was batch, whose ceiling ac-host's
      # docker-compose.buildkite.yml documents as "~25 GiB" for Nix builds.
      # Starving CI to leave an unusable ceiling here is not a trade.
      memoryShare = 0.65;
      cpuShare = 0.70; # CPUWeight 700, and cores 3-25 + siblings via the fence.
      # resources.nix defaults this to 10, which niced the inference server
      # down against everything else on the box. The tenant this tier exists
      # for is now the machine's primary workload.
      nice = 0;
    };
    batch = {
      # Left at the default 0.10 (~25 GiB), the figure ac-host's
      # docker-compose.buildkite.yml already cites to its readers as the
      # number to revisit if a build OOMs. Memory is where CI actually needs
      # headroom; CPU is where it must yield, hence the small cpuShare below.
      memoryShare = 0.10;
      # Sizes batch's OWN fence block (cores 26-27) as well as its weight.
      # Before the resources.nix fix, batch and background shared one
      # AllowedCPUs string, so a Buildkite Nix build ran on exactly the CPUs
      # the LLM was pinned to.
      cpuShare = 0.05;
    };
  };

  # ---------------------------------------------------------------------------
  # Identified as the one hard gap by docs/noop-reconciliation.md: nothing in
  # modules/platform/, host.nix or tenants.nix set this, and omitting it changes
  # the closure in a way that is tedious to trace back to its cause.
  # ---------------------------------------------------------------------------
  system.stateVersion = "26.05";
}
