# Per-host composition for ac-box.
#
# Two things live here rather than in a platform module, both for real reasons:
#
#   1. The hardware import. Nix's module system cannot make `imports` depend on
#      `config`, so driving this from homelab.host.name is infinite recursion,
#      not a style choice. It is therefore resolved with a literal path here.
#   2. Wiring tenant options to host facts. A tenant's host side
#      (hosts/ac-box/tenants/*.nix, since ADR 0009's modules left the
#      closure) declares and never reaches, so something has to hand arcade
#      the LAN address -- and that something is the host composition, which
#      is the one place allowed to know both sides.
{ config, lib, ... }:

let
  # hardware-configuration.nix is generated by nixos-generate-config and carries
  # this box's actual disks. It is TRACKED, not gitignored -- see .gitignore's
  # NOTE and commit daac96f. A flake copies only git-tracked files into the
  # store, so while it was ignored, a build from github:imkarrer/homelab found
  # no such file and took the .example branch below.
  #
  # That branch used to be described here as "a loud failure, not a quiet one".
  # It was not. Substituting the stub is a successful evaluation and a green
  # build; gate 1 found it only as a 14.7 MiB initrd shrink in diff-closures,
  # and switching it would have written boot entries for the wrong disks. The
  # stub says of itself that it will not boot a real machine, and nothing in a
  # silent `else` branch makes that loud.
  #
  # So it throws instead. Now that the real file is tracked, every clean
  # checkout has it and this branch is unreachable; reaching it means the
  # working tree lost a tracked file, which is a repair, not a fallback.
  hardwarePath =
    if builtins.pathExists ./hardware-configuration.nix then
      ./hardware-configuration.nix
    else
      throw ''
        hosts/ac-box/hardware-configuration.nix is missing.

        It is tracked in git, so a clean checkout always has it -- if it is
        gone, this working tree deleted it. Restore it; do not substitute
        hardware-configuration.nix.example, which will not boot a real machine:

          git checkout -- hosts/ac-box/hardware-configuration.nix

        or re-fetch it read-only from the box:

          scp ac-box:/var/lib/ac-host/src/hosts/ac-box/hardware-configuration.nix \
              hosts/ac-box/

        For a NEW host, generate that host's own file on that machine:

          nixos-generate-config --show-hardware-config > hosts/<name>/hardware-configuration.nix
      '';
in
{
  imports = [ hardwarePath ];

  # ---------------------------------------------------------------------------
  # Phase 1: enforcement fully off.
  #
  # The contract's assertions still run -- port collisions, the memory budget,
  # forwarded-without-justification, mgmt-without-address all fail evaluation
  # right now. Only the derivations are gated, so this configuration contributes
  # no slices, no firewall rules, no scrape configs and no /etc/homelab files.
  # That is what makes the first switch provably a no-op.
  #
  # Each flag is flipped in its own later step, smallest blast radius first:
  # inventory, then firewall, then scrape, then slices. Set explicitly rather
  # than relying on the defaults, so the phase is legible in the config itself.
  # ---------------------------------------------------------------------------
  # mkDefault, not a bare false. Setting these at normal priority made every
  # phase flip untestable: `extendModules` with `inventory = true` failed with
  # "conflicting definition values" against this file, so proving a phase's
  # blast radius required editing the repo first. With mkDefault, a variant can
  # override cleanly and each flip can be dry-activated before it is committed.
  homelab.enforce = {
    # Phase 4. Derives interface-scoped rules from the port registry. Verified
    # additive: dry-activate adds only a firewall.service RELOAD, and the
    # generated ruleset is a correct superset of what is live -- AC's forwarded
    # 8081-8096, 8181-8196 and 9600-9615 all present on enp8s0, arcade's ports
    # intact, and 11200 correctly getting no rule at all because it is declared
    # scope = "local". ac-host's global openings still exist alongside these;
    # removing them is the separate step where the exposure actually shrinks.
    firewall = lib.mkDefault true;

    # Phase 3. Writes /etc/homelab/tenants.json for boxctl. Touches no units --
    # its activation plan came out byte-identical to phase 1's.
    inventory = lib.mkDefault true;

    # Phase 5. Generates prometheus scrapeConfigs from tenant declarations,
    # reproducing the existing five job names byte-for-byte, because renaming a
    # job orphans every dashboard built on it.
    scrape = lib.mkDefault true;

    # OFF since the cutover (ADR 0010: llm-box has "no tiers, no fence";
    # homelab-ygc.13, the operator's ask the evening of 26 Sep 2026). It was
    # phase 6's flag, on from generation 31 to the cutover, and it did real
    # work while five tenants shared this machine: background.slice fenced the
    # model server to cores 3-25 under a 0.81 memory ceiling, batch fenced CI
    # to 26-27. With agent-hub alone here there is nothing to fence anything
    # from: no slices, no MemoryMax, no fence -- agent-hub-llm runs in
    # system.slice on all 28 physical cores (its own cpuset below, a placement
    # fact rather than a fence) and all 251 GiB, which is what lets llama-swap
    # keep a second 80B resident. resources.nix's budget assertion still
    # evaluates (the defaults sum to 0.9); nothing is emitted.
    #
    # THE SWITCH THAT CARRIES THIS RESTARTS THE MODEL SERVER, once. Live,
    # background.slice is an active unit with agent-hub-llm, nginx and qdrant
    # as members, and each carries Requires=background.slice. The new
    # generation has no slice files, so switch-to-configuration stops the
    # slice before activating (an active unit whose file is gone is stopped;
    # a .slice is exempt from restart, not from stop), Requires= takes the
    # three services down with it, and the target start brings them back
    # under the new files: no slice, no cpuset but the one below, 28 threads.
    # restartIfChanged = false governs a unit's OWN file comparison and does
    # not reach this; it protects every later switch, once no slice exists to
    # remove. So: dry-activate first and expect "would stop background.slice",
    # switch with the model server idle, and skip the hand restart -- the
    # switch is the restart (review of homelab-ygc.13, 26 Sep 2026).
    slices = false;
  };

  # Scraped by arcade-box's Prometheus over the LAN since the cutover left this
  # host without a collector (hosts/arcade-box/host.nix, peers.ac-box; ADR 0010).
  homelab.platform.nodeExporter.enable = true;

  # ---------------------------------------------------------------------------
  # The closure deploys itself (ADR 0006). This is the flag that makes ac-box
  # self-switching: homelab's Buildkite pipeline stages a green revision into
  # /var/lib/homelab/pending-closure.json (scripts/hub-queue-closure.sh), and
  # homelab-deploy.timer applies it at homelab.host.maintenance.window --
  # 03:00 -- with nobody present. Chosen deliberately over stage-and-wait-for-
  # a-human, because that is what queue-prod already does for the tenant tree
  # and it is reconciled only because someone remembers; 25 commits of
  # undeployed closure was what "someone remembers" looked like.
  #
  # What stands between a merge and the running system, once this is live:
  #
  #   1. Every gate in .buildkite/pipeline.yml, behind `wait: ~`. flake check
  #      builds the full toplevel; the harnesses prove the contract still
  #      rejects what it should. A red gate stages nothing.
  #   2. The quiet policy, consulted at run time from /etc/homelab/tenants.json.
  #      assetto is drainable = false; its busyCheck says BUSY whenever
  #      maintenance.json is absent, i.e. whenever nobody has drained it. The
  #      unit DEFERS to the next window in that case -- it never drains, and it
  #      fails closed if the inventory is unreadable. Exercised against the
  #      box's real inventory before this was written (modules/deploy header).
  #   3. The window itself. Persistent = false on the timer, so a missed night
  #      waits for the next one rather than firing at boot.
  #
  # Two things this flag does NOT change, said out loud:
  #
  #   - The FIRST switch after this commit is still a human one. The unit is
  #     not on the box until something applies this closure, and that
  #     something cannot be the unit. Run it with --refresh (see the runbooks
  #     for why); after it, `systemctl list-timers homelab-deploy` on the box
  #     is the proof it is armed.
  #   - hub/repos.psv's agent-push flag for homelab. Once this is live, "yes"
  #     means an agent pushing green is, indirectly, scheduling a system
  #     switch. ADR 0006 asks for that to be reconsidered AT THE SAME TIME as
  #     enabling this. Left as the operator's call, made before the enabling
  #     switch, not baked in here. AGENTS.md's migration exception (agents
  #     may switch the box) lapses when this lands; that part is written.
  #
  # Rollback is a generation: `nixos-rebuild switch --rollback` on the box, or
  # `systemctl disable --now homelab-deploy.timer` to stop the next firing
  # without undoing the switch.
  homelab.deploy.enable = true;

  # ADR 0008, decided 15 Sep 2026: a staged revision is applied as soon as CI
  # stages it, and the only thing that postpones it is somebody racing.
  #
  # The question the ADR left open was never about the lobbies -- they are out
  # of the closure's reach by construction (ac-host-static is
  # restartIfChanged = false; the sidecars are compose-owned; a slice limit
  # moves no process). It was whether arcade's file share and game servers and
  # the observability stack may bounce at any hour instead of at 03:30. The
  # operator's answer is yes, which is what makes this one line rather than
  # the `windowOnly` policy word and dry-activate parser option 2 sketched:
  # with no blast radius to distinguish, assetto's busyCheck is the whole gate,
  # and the deploy script already had it.
  #
  # What changes on this box, concretely:
  #   - a green push is live in minutes rather than up to 27 hours;
  #   - `systemctl disable --now homelab-deploy.path` is now half of stopping
  #     deploys -- the timer alone is no longer the arming switch;
  #   - between 03:00 and 03:30 nothing switches, because the tenant tree's
  #     DOWNTIME build owns that window and its drain makes the lobbies read
  #     as empty precisely when they are not free (the module's blackout);
  #   - the build runs at Nice 19 with idle IO, and the lobbies are re-checked
  #     after it and before the switch, so the exposure between "nobody is
  #     racing" and the switch is seconds rather than a whole build.
  #
  # hub/repos.psv keeps homelab at agent-push = ask, and more firmly than
  # before: under this schedule an agent pushing green is switching the box in
  # minutes, not scheduling something for 03:30. ADR 0008's Consequences says
  # to leave it at ask until the deferral has been watched working against a
  # real race.
  homelab.deploy.schedule = "continuous";

  # ---------------------------------------------------------------------------
  # agent-hub: the local coding-agent model server (tenant declared in
  # tenants.nix; host side in hosts/ac-box/tenants/agent-hub.nix, which
  # since homelab-158.11 is where the option set below is declared -- the
  # tenant's own module has left the closure, ADR 0009).
  #
  # Phase 1 only -- serving, no repo access. The runner (a Docker image the
  # agent-hub tree builds) is off everywhere and declared nowhere in this
  # closure; when it is switched on it arrives as a second stub, and its
  # egress allowlist as a host firewall fact.
  #
  # lanAddress comes from homelab.host rather than a default, same as
  # every host file does: host facts are read from the host, never
  # inherited from a tenant's guess.
  #
  # What is NOT here any more, and where it went (homelab-158.11): the
  # llama-swap table. Which engine, which GGUF, which flags per model, which
  # models may stay resident together -- all of it is llama-swap.yaml in the
  # agent-hub tree, read from the checkout at <environment.dir>. This block
  # used to set those as options the module rendered into the table; the
  # module stopped reading them on 18 Sep 2026 (.12) and they are gone with
  # it. What stays is what the HOST decides: the threads and context this
  # host affords, the port, the landing page, which models exist by
  # name and kind (the landing page lists them), and the vector store.
  services.agent-hub = {
    enable = true;
    lanAddress = config.homelab.host.networks.lan.address;

    llm = {
      enable = true;

      # The four models behind the one port, by the names llama-swap.yaml
      # spells them and the request names. Only `kind` and `description`
      # are read (the landing page's models.json); the GGUF paths, flags
      # and aliases are the table's. The reasoning behind each choice --
      # Qwen3-Coder-Next 80B-A3B over the 480B (the 480B does not fit at a
      # quantization that preserves code quality; CPU rate tracks ACTIVE
      # parameters, 3B vs 35B), the prompt-cache sizes (--cache-ram 12288
      # for coder: ~2.5 GiB per 32k conversation, agents alternate, five
      # fit; 8192 for reviewer), the embedding model at the unit's 23
      # threads not 4 (prefill is compute-bound: 6.7 s per 938-token chunk
      # at 4 threads, 16 Sep 2026), and the flags every llama backend gets
      # (-rtr: repack at load, disables mmap so the model is anonymous
      # memory under this unit's NUMAPolicy below, ~6 % prefill; --flash-attn on; --jinja: tool calls, without it every
      # request carrying `tools` is a 500; --metrics) and the ones removed
      # by measurement (--numa distribute: sets no memory policy and fights
      # the cgroup fence, 30 -> 16 tok/s; --threads-batch 46: SMT siblings
      # cost ~20 %; --mlock: nothing to pin with -rtr and no swap) -- is
      # recorded in agent-hub's docs/prefill-tuning.md and beside each
      # entry in its llama-swap.yaml, which is where a table change is made.
      models = {
        coder.description = "Qwen3-Coder-Next 80B-A3B Q8_0 -- code. Chat tab.";
        # gpt-oss-120b replaced Qwen3-Next-80B-A3B-Instruct on 20 Sep 2026
        # (homelab-e00): a second model family for bead-loop's review call,
        # which was most of what instruct did; inquire-platform's claude-*
        # aliases moved with it. The bench and the no--rtr finding are in
        # the table.
        reviewer.description = "gpt-oss-120b MXFP4 -- the second-family code reviewer; prose, judgement, inquire-platform scoring. Chat tab.";
        embed = {
          kind = "embedding";
          description = "Qwen3-Embedding-0.6B Q8_0 -- 1024-dim embeddings for Qdrant on :6333. POST /v1/embeddings.";
        };
        # Dense 4B for the cheap calls (opencode's small_model: titles,
        # summaries; pre-checks), so they never take one of coder's two
        # slots. ~12 tok/s and no faster: bandwidth-bound, all 4.3 GB read
        # per token. The bench and the thread choice are in the table.
        utility.description = "Qwen3-4B-Instruct-2507 Q8_0 -- titles, summaries, pre-checks; ~12 tok/s. Chat tab.";
        # No image models since 20 Sep 2026 (homelab-b9u): FLUX.2 klein 4B/9B
        # and Z-Image-Turbo on stable-diffusion.cpp were here from 14 Sep;
        # generating with the two not in the resident set evicted both 80Bs
        # (a minute's reload, a cold prompt cache for the next review), and
        # the ~19 GiB klein 9B held resident is wanted for a second-family
        # reviewer (homelab-e00) and a utility model (homelab-8r5).
      };

      # One per PHYSICAL core, all 28 of them, since the fence came down
      # (homelab-ygc.13; it was 23, the cores background.slice's fence
      # granted). Not the host's 56: llama.cpp's generation threads want one
      # per physical core, and oversubscribing onto the SMT siblings makes a
      # memory-bandwidth-bound workload ~20 % slower, not faster (agent-hub
      # docs/prefill-tuning.md). Whether one instance should span both
      # sockets or one 80B be pinned per NUMA node is a llama-swap.yaml
      # decision for tuning time (ADR 0010), not a host fact.
      threads = 28;

      # Not larger, even though the model natively supports 262144 and
      # the machine would hold the KV cache for it. The binding
      # constraint on CPU is PREFILL, not RAM: prompt processing is
      # compute-bound, this is Broadwell (no AVX-512), and ingesting a
      # six-figure-token prompt would take longer than the answer is worth.
      # Raise it once a measured prefill rate says it is affordable. As of
      # 14 Sep 2026 one does -- 128 tok/s at 4k, 119 at 8k with the ik
      # engine -- so the full 32k is under five minutes and more is a routing
      # decision (homelab-route) rather than a hardware one. Not raised in
      # the same change that swapped the engine; one variable at a time.
      contextSize = 32768;

      # nginx in front, so http://<lan>:8100/ is a page that lists chat
      # models and the embedding model apart and opens each chat model in
      # its own UI. llama-swap's /ui cannot: it shows every model on every
      # playground tab, and the first person to try it picked the (then)
      # image model on the Chat tab. llama-swap itself moves to
      # 127.0.0.1:8100; nginx.service joins this tenant's units in
      # tenants.nix as the contract's list of what this tenant owns (no slice is derived from it on this host since homelab-ygc.13).
      landingPage = true;
    };

    # Qdrant on the LAN address, :6333, the store the `embed` model above
    # writes into; gRPC is off so that is its only port. qdrant.service
    # and /var/lib/qdrant join this tenant in tenants.nix -- the same
    # pairing rule as nginx.service. Empty until something indexes into it
    # (homelab-jtn); agent-hub's scripts/vectors-smoke.sh proves the pair
    # works without leaving data behind.
    vectors.enable = true;
  };

  # A closure switch must not restart the model server. switch-to-configuration
  # restarts a unit whose file changed; six restarts on 18 Sep 2026, four of
  # them from generations 90-93 that touched nothing the model needed, each
  # dropped the resident 85 GB model and the prompt cache mid-request (a
  # bead-loop review call waited five minutes and got a 502). The unit is
  # restarted on purpose by exactly one thing: the environment pull
  # (modules/tenant/environment-pull.nix, "restart the stub"), under the
  # tenant's quiet policy, when a new agent-hub sha is staged. A changed
  # unit file applies at that next deliberate restart, or at a human's
  # `systemctl restart agent-hub-llm` -- the same shape as the pull unit's
  # own restartIfChanged = false and modules/deploy's. homelab-7bu.
  systemd.services.agent-hub-llm = {
    restartIfChanged = false;
    stopIfChanged = false;
  };

  # Where the model server's threads and memory go. Set directly on the
  # unit rather than as a stub field because every value is a fact about
  # THIS host's sockets, not part of the unit's skeleton (schema.nix says
  # which keys are). Merges with what modules/tenant/environment.nix emits
  # -- different keys, no conflict.
  systemd.services.agent-hub-llm.serviceConfig = {
    # Every physical core and none of the SMT siblings. Not a fence -- there
    # is no other tenant on this host to keep away from (homelab-ygc.13
    # took the fence down with the slices) -- but a placement fact of the
    # same class as the NUMA policy below: agent-hub's docs/prefill-tuning.md
    # measured the same engine and thread count at 99 tok/s prefill on a
    # cpuset that included the siblings and 122 on physical cores only, and
    # attributes the gain to the cpuset, not the count. This was "3-25" while
    # background.slice fenced the unit; now it is the whole machine's cores.
    # Deleting this line hands the unit all 56 CPUs; `scripts/bench/bench.sh`
    # in the agent-hub tree is how to decide that, not a guess.
    AllowedCPUs = "0-27";


    # Spread the model over both sockets' memory controllers. Without a
    # policy the 85 GB landed wherever the loading thread ran -- 100 % on
    # node 1, measured -- and half the cores read every weight across QPI.
    # Interleave is what lets a two-socket thread set beat a one-socket one
    # with these kernels (121 vs 78 tok/s prefill, 12.5 vs 8.5 generation).
    # -rtr (llama-swap.yaml's llama_extra) makes this the policy for the model itself, not just
    # for what the page cache happens to fault under it.
    NUMAPolicy = "interleave";
    NUMAMask = "0-1";
  };

  # ---------------------------------------------------------------------------
  # ADR 0009 step 1: agent-hub-llm.service, run from agent-hub's flox
  # environment -- and since homelab-158.11 the WHOLE unit, declared here.
  #
  # ON as of homelab-158.3 -- and flipping it was that bead's LAST commit,
  # landed as a separate push, for a reason this file cannot enforce:
  # enable = true makes ExecStart an activation of `dir`, and the switch
  # that carries it restarts the unit. Against an empty `dir` that
  # activation cannot succeed and Restart= loops it. So `dir` must already
  # hold a checkout of agent-hub, owned by the agent-hub user and activated
  # once online (docs/flox-findings.md 1), BEFORE this line is true.
  # Declaring the stub (units below) is what makes
  # modules/tenant/environment-pull.nix keep that checkout, enable on or
  # off; the order is: land the stub with this false, push agent-hub main
  # so its trigger stages a sha, watch hub-status say `agent-hub env:
  # staged X / applied X (run ...)`, THEN land this true. hub-status names
  # the state where that order was not followed ("the stub is ON and
  # nothing has been applied"). Back to false is the rollback: the unit's
  # ExecStart becomes environment.nix's refusing placeholder at the next
  # switch (there is no module to fall back to since .11) and the checkout
  # stays where it is.
  #
  # What the stub declares, since .11, is the unit: `command` and the
  # seven AGENT_HUB_* variables the manifest's hook would otherwise default
  # (set here, from THIS file's values, so no default in the tenant tree is
  # load-bearing on the box -- the .1 review's finding 1), and the skeleton
  # the retired modules/agent-hub.nix used to supply: the description,
  # User=/Group=agent-hub (the schema's default, the tenant's name),
  # Restart=on-failure/RestartSec=5 (defaults), After=/Wants=
  # network-online.target and WantedBy=multi-user.target (defaults), and
  # TimeoutStopSec=90 -- llama-swap stops its backends itself on SIGTERM,
  # and a model mid-load needs time to die cleanly before systemd
  # escalates. No slice on this host since homelab-ygc.13 (enforce.slices
  # is off); the cpuset and NUMA policy are the host's, just above. Every value below
  # is read from the same option a second reader has (services.agent-hub,
  # hosts/ac-box/tenants/agent-hub.nix) so the two cannot drift.
  homelab.tenants.agent-hub.environment =
    let
      llm = config.services.agent-hub;
      env = config.homelab.tenants.agent-hub.environment;
      # Loopback when nginx owns the LAN side of the port (landingPage),
      # the LAN address otherwise.
      listen = "${if llm.llm.landingPage then "127.0.0.1" else llm.lanAddress}:${toString llm.llm.port}";
      modelCount = builtins.length (builtins.attrNames llm.llm.models);
    in
    {
      enable = true;
      # homelab-ygc.14, the ADR 0010 amendment: this host has had no CI
      # agent since the cutover, so the edge that stages a green agent-hub
      # sha (queue-environment, run by the agent) writes on arcade-box,
      # where no stub exists, and the pull unit here idles. With poll on,
      # agent-hub-environment-poll asks GitHub for main's HEAD and its
      # commit status every ten minutes and stages a green one here, in
      # the record queue-environment writes; the pull unit is unchanged
      # (modules/tenant/environment-poll.nix).
      poll = true;
      # dir: left null, i.e. derived by modules/tenant/environment.nix to
      # <state dir>/env = /var/lib/agent-hub/env, which is right; `env.dir`
      # above reads the resolved value, so the -config path and the
      # activation share one spelling.
      units."agent-hub-llm.service" = {
        # The retired module's description, verbatim: the model count is
        # the one live thing the models table still says about the unit.
        description = "agent-hub model server: llama-swap over ${toString modelCount} models (LAN only)";
        timeoutStopSec = 90;
        command = [
          "llama-swap"
          "-config"
          "${toString env.dir}/llama-swap.yaml"
          "-listen"
          listen
        ];
        environment = {
          AGENT_HUB_MODELS = "${toString llm.dataDir}/models";
          AGENT_HUB_THREADS = toString llm.llm.threads;
          AGENT_HUB_CTX = toString llm.llm.contextSize;
          AGENT_HUB_LISTEN = listen;
          # llama-swap.yaml's `startPort`; one spelling, the option's.
          AGENT_HUB_BACKEND_PORT = toString llm.llm.backendPort;
          AGENT_HUB_SWAP_CONFIG = "${toString env.dir}/llama-swap.yaml";
        };
      };
    };

  # ---------------------------------------------------------------------------
  # No tier table (homelab-ygc.13). From 8 Sep to 26 Sep 2026 this file
  # carried the shares that pointed a five-tenant machine at the model server
  # -- background at 0.81 of memory and cores 3-25, batch fenced to 26-27,
  # critical and interactive cut to 0.02 each -- and every number in it was
  # measured; `git log -p` on this block is that record. With
  # homelab.enforce.slices off and agent-hub alone here, resources.nix's
  # defaults are inert and the block would be a table nothing reads.
  # ---------------------------------------------------------------------------

  # ---------------------------------------------------------------------------
  # Identified as the one hard gap by docs/noop-reconciliation.md: nothing in
  # modules/platform/, host.nix or tenants.nix set this, and omitting it changes
  # the closure in a way that is tedious to trace back to its cause.
  # ---------------------------------------------------------------------------
  system.stateVersion = "26.05";
}
