# Per-host composition for ac-box.
#
# Two things live here rather than in a platform module, both for real reasons:
#
#   1. The hardware import. Nix's module system cannot make `imports` depend on
#      `config`, so driving this from homelab.host.name is infinite recursion,
#      not a style choice. It is therefore resolved with a literal path here.
#   2. Wiring tenant options to host facts. A tenant's host side
#      (hosts/ac-box/tenants/*.nix, since ADR 0009's modules left the
#      closure) declares and never reaches, so something has to hand arcade
#      the LAN address -- and that something is the host composition, which
#      is the one place allowed to know both sides.
{ config, lib, ... }:

let
  # hardware-configuration.nix is generated by nixos-generate-config and carries
  # this box's actual disks. It is TRACKED, not gitignored -- see .gitignore's
  # NOTE and commit daac96f. A flake copies only git-tracked files into the
  # store, so while it was ignored, a build from github:imkarrer/homelab found
  # no such file and took the .example branch below.
  #
  # That branch used to be described here as "a loud failure, not a quiet one".
  # It was not. Substituting the stub is a successful evaluation and a green
  # build; gate 1 found it only as a 14.7 MiB initrd shrink in diff-closures,
  # and switching it would have written boot entries for the wrong disks. The
  # stub says of itself that it will not boot a real machine, and nothing in a
  # silent `else` branch makes that loud.
  #
  # So it throws instead. Now that the real file is tracked, every clean
  # checkout has it and this branch is unreachable; reaching it means the
  # working tree lost a tracked file, which is a repair, not a fallback.
  hardwarePath =
    if builtins.pathExists ./hardware-configuration.nix then
      ./hardware-configuration.nix
    else
      throw ''
        hosts/ac-box/hardware-configuration.nix is missing.

        It is tracked in git, so a clean checkout always has it -- if it is
        gone, this working tree deleted it. Restore it; do not substitute
        hardware-configuration.nix.example, which will not boot a real machine:

          git checkout -- hosts/ac-box/hardware-configuration.nix

        or re-fetch it read-only from the box:

          scp ac-box:/var/lib/ac-host/src/hosts/ac-box/hardware-configuration.nix \
              hosts/ac-box/

        For a NEW host, generate that host's own file on that machine:

          nixos-generate-config --show-hardware-config > hosts/<name>/hardware-configuration.nix
      '';
in
{
  imports = [ hardwarePath ];

  # ---------------------------------------------------------------------------
  # Phase 1: enforcement fully off.
  #
  # The contract's assertions still run -- port collisions, the memory budget,
  # forwarded-without-justification, mgmt-without-address all fail evaluation
  # right now. Only the derivations are gated, so this configuration contributes
  # no slices, no firewall rules, no scrape configs and no /etc/homelab files.
  # That is what makes the first switch provably a no-op.
  #
  # Each flag is flipped in its own later step, smallest blast radius first:
  # inventory, then firewall, then scrape, then slices. Set explicitly rather
  # than relying on the defaults, so the phase is legible in the config itself.
  # ---------------------------------------------------------------------------
  # mkDefault, not a bare false. Setting these at normal priority made every
  # phase flip untestable: `extendModules` with `inventory = true` failed with
  # "conflicting definition values" against this file, so proving a phase's
  # blast radius required editing the repo first. With mkDefault, a variant can
  # override cleanly and each flip can be dry-activated before it is committed.
  homelab.enforce = {
    # Phase 4. Derives interface-scoped rules from the port registry. Verified
    # additive: dry-activate adds only a firewall.service RELOAD, and the
    # generated ruleset is a correct superset of what is live -- AC's forwarded
    # 8081-8096, 8181-8196 and 9600-9615 all present on enp8s0, arcade's ports
    # intact, and 11200 correctly getting no rule at all because it is declared
    # scope = "local". ac-host's global openings still exist alongside these;
    # removing them is the separate step where the exposure actually shrinks.
    firewall = lib.mkDefault true;

    # Phase 3. Writes /etc/homelab/tenants.json for boxctl. Touches no units --
    # its activation plan came out byte-identical to phase 1's.
    inventory = lib.mkDefault true;

    # Phase 5. Generates prometheus scrapeConfigs from tenant declarations,
    # reproducing the existing five job names byte-for-byte, because renaming a
    # job orphans every dashboard built on it.
    scrape = lib.mkDefault true;

    # Phase 6. The only flag with real service churn, deliberately taken in its
    # own switch rather than riding along with the three quiet ones.
    #
    # Safe now because resources.nix assigns Slice= only where tier != critical
    # AND quiet.drainable. Slice= applies at unit start, so assigning it bounces
    # the unit -- and bouncing ac-host-static means `docker rm -f` on three live
    # race servers. assetto is therefore never sliced, which costs nothing: the
    # guarantee comes from AllowedCPUs fencing background and batch away from
    # the cores races use, not from confining races.
    slices = lib.mkDefault true;
  };

  # ---------------------------------------------------------------------------
  # CI stack (Buildkite agent + MinIO), adopted under systemd (beads
  # homelab-bqo.12). Was hand-started via `docker compose up -d --build`, per
  # the compose file's own header -- no lifecycle management, no start-on-boot,
  # no supervised restart. Not a resource-fencing fix (that's already handled
  # by the compose file's own cgroup_parent, see homelab-bqo.27): this is
  # purely about the stack surviving a reboot without a human remembering to
  # run docker compose by hand.
  #
  # THIS FLAG MUST NOT REACH THE BOX BEFORE THE HAND-STARTED STACK IS STOPPED.
  # docker-compose up -d --build against the same project name as an
  # already-running stack is a port/network collision, not a clean takeover --
  # see modules/ci/default.nix's own HAZARD 1. The runbook sequences this:
  # commit and push this line, but do not switch until the box-side stop +
  # volume/port verification (module header, steps 1-4) is done.
  homelab.ci.enable = true;

  # modules/ci/default.nix deliberately leaves wantedBy unset -- "a decision
  # for whoever wires this module in" -- because the whole point of this bead
  # is starting on boot instead of a human remembering docker compose up -d.
  systemd.services.ac-host-ci.wantedBy = [ "multi-user.target" ];

  # The ci tenant as a flox environment (ADR 0009 step 3, modules/ci/default
  # .nix's NATIVE header): the agent, minio and its init as stubs from
  # homelab's own .flox/ checked out at /var/lib/ci/env, in place of the
  # compose unit. OFF: the line above is the whole of what runs, and the
  # closure is byte-identical with or without this block (homelab-158.6).
  # Flipping it is the cutover, docs/runbook-ci-native-cutover.md -- one
  # push, after the box-side steps, never before -- because the switch that
  # carries `true` stops the compose stack. jobEnvironment is set here
  # regardless, since it reaches nothing while native is off: the paths
  # ac-host's pipeline reads on the box, spelled from the tenant's own
  # options rather than repeated (compose/docker-compose.buildkite.yml had
  # them as literals), plus the two non-secret pages defaults that file
  # carried; the secret and identity values are the ci-env render's.
  # ON 18 Sep 2026 (runbook step 1: pre-flight done, MinIO data copied to
  # /var/lib/ci/minio, queue drained), OFF 19 Sep 2026 by ADR 0011: a CI job
  # is not a deployment to the box, so it runs in a container, and the
  # container the agent ran in was also the job's sandbox -- /bin/bash, UTC,
  # a checkout that goes with it, processes that die with a cancelled job.
  # inquire-platform's memory-transport smoke fails on the native agent
  # only (inquire inq-29g). The switch that carries false stops the three
  # stubs and starts the compose unit again (runbook section 6). Back to
  # true only once jobs have a sandbox of their own.
  homelab.ci.native.enable = false;
  homelab.ci.native.jobEnvironment =
    let
      ac = config.services.ac-host;
      state = toString ac.stateDir;
    in
    {
      AC_STATE = state;
      AC_CONTENT = "${state}/content";
      AC_SRC = toString ac.repoDir;
      AC_BUILD = "${state}/build";
      AC_SERVE_CONTENT = "${state}/content";
      AC_PAGES_CHECKOUT = "";
      GITHUB_STATUS_BRANCH = "main";
    };

  # ---------------------------------------------------------------------------
  # The closure deploys itself (ADR 0006). This is the flag that makes ac-box
  # self-switching: homelab's Buildkite pipeline stages a green revision into
  # /var/lib/homelab/pending-closure.json (scripts/hub-queue-closure.sh), and
  # homelab-deploy.timer applies it at homelab.host.maintenance.window --
  # 03:00 -- with nobody present. Chosen deliberately over stage-and-wait-for-
  # a-human, because that is what queue-prod already does for the tenant tree
  # and it is reconciled only because someone remembers; 25 commits of
  # undeployed closure was what "someone remembers" looked like.
  #
  # What stands between a merge and the running system, once this is live:
  #
  #   1. Every gate in .buildkite/pipeline.yml, behind `wait: ~`. flake check
  #      builds the full toplevel; the harnesses prove the contract still
  #      rejects what it should. A red gate stages nothing.
  #   2. The quiet policy, consulted at run time from /etc/homelab/tenants.json.
  #      assetto is drainable = false; its busyCheck says BUSY whenever
  #      maintenance.json is absent, i.e. whenever nobody has drained it. The
  #      unit DEFERS to the next window in that case -- it never drains, and it
  #      fails closed if the inventory is unreadable. Exercised against the
  #      box's real inventory before this was written (modules/deploy header).
  #   3. The window itself. Persistent = false on the timer, so a missed night
  #      waits for the next one rather than firing at boot.
  #
  # Two things this flag does NOT change, said out loud:
  #
  #   - The FIRST switch after this commit is still a human one. The unit is
  #     not on the box until something applies this closure, and that
  #     something cannot be the unit. Run it with --refresh (see the runbooks
  #     for why); after it, `systemctl list-timers homelab-deploy` on the box
  #     is the proof it is armed.
  #   - hub/repos.psv's agent-push flag for homelab. Once this is live, "yes"
  #     means an agent pushing green is, indirectly, scheduling a system
  #     switch. ADR 0006 asks for that to be reconsidered AT THE SAME TIME as
  #     enabling this. Left as the operator's call, made before the enabling
  #     switch, not baked in here. AGENTS.md's migration exception (agents
  #     may switch the box) lapses when this lands; that part is written.
  #
  # Rollback is a generation: `nixos-rebuild switch --rollback` on the box, or
  # `systemctl disable --now homelab-deploy.timer` to stop the next firing
  # without undoing the switch.
  homelab.deploy.enable = true;

  # ADR 0008, decided 15 Sep 2026: a staged revision is applied as soon as CI
  # stages it, and the only thing that postpones it is somebody racing.
  #
  # The question the ADR left open was never about the lobbies -- they are out
  # of the closure's reach by construction (ac-host-static is
  # restartIfChanged = false; the sidecars are compose-owned; a slice limit
  # moves no process). It was whether arcade's file share and game servers and
  # the observability stack may bounce at any hour instead of at 03:30. The
  # operator's answer is yes, which is what makes this one line rather than
  # the `windowOnly` policy word and dry-activate parser option 2 sketched:
  # with no blast radius to distinguish, assetto's busyCheck is the whole gate,
  # and the deploy script already had it.
  #
  # What changes on this box, concretely:
  #   - a green push is live in minutes rather than up to 27 hours;
  #   - `systemctl disable --now homelab-deploy.path` is now half of stopping
  #     deploys -- the timer alone is no longer the arming switch;
  #   - between 03:00 and 03:30 nothing switches, because the tenant tree's
  #     DOWNTIME build owns that window and its drain makes the lobbies read
  #     as empty precisely when they are not free (the module's blackout);
  #   - the build runs at Nice 19 with idle IO, and the lobbies are re-checked
  #     after it and before the switch, so the exposure between "nobody is
  #     racing" and the switch is seconds rather than a whole build.
  #
  # hub/repos.psv keeps homelab at agent-push = ask, and more firmly than
  # before: under this schedule an agent pushing green is switching the box in
  # minutes, not scheduling something for 03:30. ADR 0008's Consequences says
  # to leave it at ask until the deferral has been watched working against a
  # real race.
  homelab.deploy.schedule = "continuous";

  # ---------------------------------------------------------------------------
  # Tenants, reproducing ac-box's live configuration exactly.
  # ---------------------------------------------------------------------------

  services.ac-host = {
    enable = true;
    repoDir = "/var/lib/ac-host/src";
    stateDir = "/var/lib/ac-host";
    authOpen = false;
    requiredRole = "ac-practice";
  };

  services.ac-host-dev = {
    enable = true;
    stateDir = "/var/lib/ac-host-dev";
  };

  # arcade's host side (hosts/ac-box/tenants/arcade.nix): the user, the
  # directories, the SMB and rsync exports. lanAddress has no default there
  # on purpose -- it was once duplicated into two tenant modules and
  # drifted -- so the host fact is passed in from homelab.host here. The
  # two game servers are the stubs further down, not options here.
  services.arcade-hub = {
    enable = true;
    lanAddress = config.homelab.host.networks.lan.address;
    rsync.enable = true;
  };

  # ---------------------------------------------------------------------------
  # agent-hub: the local coding-agent model server (tenant declared in
  # tenants.nix; host side in hosts/ac-box/tenants/agent-hub.nix, which
  # since homelab-158.11 is where the option set below is declared -- the
  # tenant's own module has left the closure, ADR 0009).
  #
  # Phase 1 only -- serving, no repo access. The runner (a Docker image the
  # agent-hub tree builds) is off everywhere and declared nowhere in this
  # closure; when it is switched on it arrives as a second stub, and its
  # egress allowlist as a host firewall fact.
  #
  # lanAddress comes from homelab.host rather than a default, same as
  # services.arcade-hub above: host facts are read from the host, never
  # inherited from a tenant's guess.
  #
  # What is NOT here any more, and where it went (homelab-158.11): the
  # llama-swap table. Which engine, which GGUF, which flags per model, which
  # models may stay resident together -- all of it is llama-swap.yaml in the
  # agent-hub tree, read from the checkout at <environment.dir>. This block
  # used to set those as options the module rendered into the table; the
  # module stopped reading them on 18 Sep 2026 (.12) and they are gone with
  # it. What stays is what the HOST decides: the threads and context the
  # tier's fence affords, the port, the landing page, which models exist by
  # name and kind (the landing page lists them), and the vector store.
  services.agent-hub = {
    enable = true;
    lanAddress = config.homelab.host.networks.lan.address;

    llm = {
      enable = true;

      # The four models behind the one port, by the names llama-swap.yaml
      # spells them and the request names. Only `kind` and `description`
      # are read (the landing page's models.json); the GGUF paths, flags
      # and aliases are the table's. The reasoning behind each choice --
      # Qwen3-Coder-Next 80B-A3B over the 480B (the 480B does not fit at a
      # quantization that preserves code quality; CPU rate tracks ACTIVE
      # parameters, 3B vs 35B), the prompt-cache sizes (--cache-ram 12288
      # for coder: ~2.5 GiB per 32k conversation, agents alternate, five
      # fit; 8192 for instruct), the embedding model at the unit's 23
      # threads not 4 (prefill is compute-bound: 6.7 s per 938-token chunk
      # at 4 threads, 16 Sep 2026), and the flags every llama backend gets
      # (-rtr: repack at load, disables mmap so the model is anonymous
      # memory under this unit's NUMAPolicy below, ~6 % prefill; --flash-attn on; --jinja: tool calls, without it every
      # request carrying `tools` is a 500; --metrics) and the ones removed
      # by measurement (--numa distribute: sets no memory policy and fights
      # the cgroup fence, 30 -> 16 tok/s; --threads-batch 46: SMT siblings
      # cost ~20 %; --mlock: nothing to pin with -rtr and no swap) -- is
      # recorded in agent-hub's docs/prefill-tuning.md and beside each
      # entry in its llama-swap.yaml, which is where a table change is made.
      models = {
        coder.description = "Qwen3-Coder-Next 80B-A3B Q8_0 -- code. Chat tab.";
        instruct.description = "Qwen3-Next-80B-A3B-Instruct Q8_0 -- prose, judgement, inquire-platform scoring. Chat tab.";
        embed = {
          kind = "embedding";
          description = "Qwen3-Embedding-0.6B Q8_0 -- 1024-dim embeddings for Qdrant on :6333. POST /v1/embeddings.";
        };
        # Dense 4B for the cheap calls (opencode's small_model: titles,
        # summaries; pre-checks), so they never take one of coder's two
        # slots. ~12 tok/s and no faster: bandwidth-bound, all 4.3 GB read
        # per token. The bench and the thread choice are in the table.
        utility.description = "Qwen3-4B-Instruct-2507 Q8_0 -- titles, summaries, pre-checks; ~12 tok/s. Chat tab.";
        # No image models since 20 Sep 2026 (homelab-b9u): FLUX.2 klein 4B/9B
        # and Z-Image-Turbo on stable-diffusion.cpp were here from 14 Sep;
        # generating with the two not in the resident set evicted both 80Bs
        # (a minute's reload, a cold prompt cache for the next review), and
        # the ~19 GiB klein 9B held resident is wanted for a second-family
        # reviewer (homelab-e00) and a utility model (homelab-8r5).
      };

      # PHYSICAL cores inside background.slice's fence, not logical threads
      # and not the host's 56. The fence (resources.nix) gives background
      # cores 3-25 plus their SMT siblings; llama.cpp's generation threads
      # want one per physical core -- oversubscribing to the siblings makes
      # a memory-bandwidth-bound workload slower, not faster.
      #
      # This is the option's own documented contract: "must match the CPU
      # allowance the platform's tenant tier actually grants this
      # service". If the tier shares below move, this moves with them.
      threads = 23;

      # Not larger, even though the model natively supports 262144 and
      # background.slice's ceiling would hold the KV cache for it. The binding
      # constraint on CPU is PREFILL, not RAM: prompt processing is
      # compute-bound, this is Broadwell (no AVX-512), and ingesting a
      # six-figure-token prompt would take longer than the answer is worth.
      # Raise it once a measured prefill rate says it is affordable. As of
      # 14 Sep 2026 one does -- 128 tok/s at 4k, 119 at 8k with the ik
      # engine -- so the full 32k is under five minutes and more is a routing
      # decision (homelab-route) rather than a hardware one. Not raised in
      # the same change that swapped the engine; one variable at a time.
      contextSize = 32768;

      # nginx in front, so http://<lan>:8100/ is a page that lists chat
      # models and the embedding model apart and opens each chat model in
      # its own UI. llama-swap's /ui cannot: it shows every model on every
      # playground tab, and the first person to try it picked the (then)
      # image model on the Chat tab. llama-swap itself moves to
      # 127.0.0.1:8100; nginx.service joins this tenant's units in
      # tenants.nix so it lives in the same slice.
      landingPage = true;
    };

    # Qdrant on the LAN address, :6333, the store the `embed` model above
    # writes into; gRPC is off so that is its only port. qdrant.service
    # and /var/lib/qdrant join this tenant in tenants.nix -- the same
    # pairing rule as nginx.service. Empty until something indexes into it
    # (homelab-jtn); agent-hub's scripts/vectors-smoke.sh proves the pair
    # works without leaving data behind.
    vectors.enable = true;
  };

  # A closure switch must not restart the model server. switch-to-configuration
  # restarts a unit whose file changed; six restarts on 18 Sep 2026, four of
  # them from generations 90-93 that touched nothing the model needed, each
  # dropped the resident 85 GB model and the prompt cache mid-request (a
  # bead-loop review call waited five minutes and got a 502). The unit is
  # restarted on purpose by exactly one thing: the environment pull
  # (modules/tenant/environment-pull.nix, "restart the stub"), under the
  # tenant's quiet policy, when a new agent-hub sha is staged. A changed
  # unit file applies at that next deliberate restart, or at a human's
  # `systemctl restart agent-hub-llm` -- the same shape as the pull unit's
  # own restartIfChanged = false and modules/deploy's. homelab-7bu.
  systemd.services.agent-hub-llm = {
    restartIfChanged = false;
    stopIfChanged = false;
  };

  # Where the model server's threads and memory go. Set directly on the
  # unit rather than as a stub field because every value is a fact about
  # THIS host's sockets and fence, not part of the unit's skeleton
  # (schema.nix says which keys are). Merges with what
  # modules/tenant/environment.nix emits -- different keys, no conflict.
  systemd.services.agent-hub-llm.serviceConfig = {
    # Physical cores only: the fence background.slice gets from resources.nix
    # is 3-25 plus SMT siblings 31-53, and a child cgroup's cpuset must be a
    # subset of its parent's -- this is that subset. With the siblings
    # available the scheduler lands some of the 23 compute threads on them
    # and prefill drops ~20 % (99 -> 122 tok/s with this line, batch 2 in
    # agent-hub docs/prefill-tuning.md). Coupled to `threads = 23` above and
    # to the tier shares below exactly as that option's comment says: if the
    # fence moves, this moves with it.
    AllowedCPUs = "3-25";

    # Spread the model over both sockets' memory controllers. Without a
    # policy the 85 GB landed wherever the loading thread ran -- 100 % on
    # node 1, measured -- and half the cores read every weight across QPI.
    # Interleave is what lets a two-socket thread set beat a one-socket one
    # with these kernels (121 vs 78 tok/s prefill, 12.5 vs 8.5 generation).
    # -rtr (llama-swap.yaml's llama_extra) makes this the policy for the model itself, not just
    # for what the page cache happens to fault under it.
    NUMAPolicy = "interleave";
    NUMAMask = "0-1";
  };

  # ---------------------------------------------------------------------------
  # ADR 0009 step 1: agent-hub-llm.service, run from agent-hub's flox
  # environment -- and since homelab-158.11 the WHOLE unit, declared here.
  #
  # ON as of homelab-158.3 -- and flipping it was that bead's LAST commit,
  # landed as a separate push, for a reason this file cannot enforce:
  # enable = true makes ExecStart an activation of `dir`, and the switch
  # that carries it restarts the unit. Against an empty `dir` that
  # activation cannot succeed and Restart= loops it. So `dir` must already
  # hold a checkout of agent-hub, owned by the agent-hub user and activated
  # once online (docs/flox-findings.md 1), BEFORE this line is true.
  # Declaring the stub (units below) is what makes
  # modules/tenant/environment-pull.nix keep that checkout, enable on or
  # off; the order is: land the stub with this false, push agent-hub main
  # so its trigger stages a sha, watch hub-status say `agent-hub env:
  # staged X / applied X (run ...)`, THEN land this true. hub-status names
  # the state where that order was not followed ("the stub is ON and
  # nothing has been applied"). Back to false is the rollback: the unit's
  # ExecStart becomes environment.nix's refusing placeholder at the next
  # switch (there is no module to fall back to since .11) and the checkout
  # stays where it is.
  #
  # What the stub declares, since .11, is the unit: `command` and the
  # seven AGENT_HUB_* variables the manifest's hook would otherwise default
  # (set here, from THIS file's values, so no default in the tenant tree is
  # load-bearing on the box -- the .1 review's finding 1), and the skeleton
  # the retired modules/agent-hub.nix used to supply: the description,
  # User=/Group=agent-hub (the schema's default, the tenant's name),
  # Restart=on-failure/RestartSec=5 (defaults), After=/Wants=
  # network-online.target and WantedBy=multi-user.target (defaults), and
  # TimeoutStopSec=90 -- llama-swap stops its backends itself on SIGTERM,
  # and a model mid-load needs time to die cleanly before systemd
  # escalates. background.slice is tenants.nix's via resources.nix; the
  # cpuset and NUMA policy are the host's, just above. Every value below
  # is read from the same option a second reader has (services.agent-hub,
  # hosts/ac-box/tenants/agent-hub.nix) so the two cannot drift.
  homelab.tenants.agent-hub.environment =
    let
      llm = config.services.agent-hub;
      env = config.homelab.tenants.agent-hub.environment;
      # Loopback when nginx owns the LAN side of the port (landingPage),
      # the LAN address otherwise.
      listen = "${if llm.llm.landingPage then "127.0.0.1" else llm.lanAddress}:${toString llm.llm.port}";
      modelCount = builtins.length (builtins.attrNames llm.llm.models);
    in
    {
      enable = true;
      # dir: left null, i.e. derived by modules/tenant/environment.nix to
      # <state dir>/env = /var/lib/agent-hub/env, which is right; `env.dir`
      # above reads the resolved value, so the -config path and the
      # activation share one spelling.
      units."agent-hub-llm.service" = {
        # The retired module's description, verbatim: the model count is
        # the one live thing the models table still says about the unit.
        description = "agent-hub model server: llama-swap over ${toString modelCount} models (LAN only)";
        timeoutStopSec = 90;
        command = [
          "llama-swap"
          "-config"
          "${toString env.dir}/llama-swap.yaml"
          "-listen"
          listen
        ];
        environment = {
          AGENT_HUB_MODELS = "${toString llm.dataDir}/models";
          AGENT_HUB_THREADS = toString llm.llm.threads;
          AGENT_HUB_CTX = toString llm.llm.contextSize;
          AGENT_HUB_LISTEN = listen;
          # llama-swap.yaml's `startPort`; one spelling, the option's.
          AGENT_HUB_BACKEND_PORT = toString llm.llm.backendPort;
          AGENT_HUB_SWAP_CONFIG = "${toString env.dir}/llama-swap.yaml";
        };
      };
    };

  # ---------------------------------------------------------------------------
  # ADR 0009 step 2: arcade's two game servers, run from home-arcade's flox
  # environment -- and the FloxHub dogfood: nothing the servers need at run
  # time comes from the tree (both read only /var/lib/arcade), so the deploy
  # unit is a GENERATION of imkarrer/arcade (source.kind = floxhub), pushed by
  # home-arcade's CI on green (its scripts/ci_push.sh) and staged here the way
  # agent-hub's sha is. modules/tenant/environment-pull.nix's "KIND = FLOXHUB"
  # header is the mechanism; docs/flox-findings.md 3 the record.
  #
  # Since homelab-158.11 these two stubs are the whole units: what
  # home-arcade's modules/arcade-hub.nix used to supply -- the descriptions,
  # User=/Group=arcade (the schema's default), WorkingDirectory= under the
  # state dir (Mindustry writes config/ under its cwd), Restart=on-failure/
  # RestartSec=5, After=/Wants= network-online.target, WantedBy=
  # multi-user.target (all defaults) -- is spelled here or defaulted by
  # schema.nix. interactive.slice is tenants.nix's via resources.nix; the
  # firewall holes are the tenant's port claims there.
  #
  # The values are the module's own argv minus the store path, read from
  # the same options (services.arcade-hub.*, hosts/ac-box/tenants/arcade.nix)
  # the exports read, so the two cannot drift:
  #
  #   freeciv    freeciv-server --bind <lan> --port <freeciv.port>
  #                --saves <state>/freeciv --log <state>/freeciv/server.log
  #   mindustry  mindustry-server, JAVA_TOOL_OPTIONS=-Xms256M -Xmx1G (the
  #              module's java flags), and the three console lines the
  #              module's wrapper once piped into java carried as the unit's
  #              stdin: Mindustry takes startup commands on stdin, one per
  #              line, and joins argv into one command. The nixpkgs
  #              mindustry-server wrapper execs java, so the unit's main PID
  #              is java and stdin reaches it through `flox activate --`
  #              (home-arcade's CI gate feeds it `version` the same way).
  #
  # NO ARCADE_* variables, on purpose: the manifest has no [hook] (a
  # `${X:?}` hook fails CI's activation and the pull's warm, both of which
  # know no LAN address -- home-arcade's manifest header), so every host
  # fact is argv or stdin here and nothing in the tenant tree can default
  # one. The `[services]` blocks in the manifest are the developer's shell
  # (docs/flox-findings.md 2), not what runs here.
  homelab.tenants.arcade.environment =
    let
      hub = config.services.arcade-hub;
      state = toString hub.stateDir;
    in
    {
      # ON since 18 Sep 2026 12:27 CDT: generation 1 of imkarrer/arcade was
      # pulled, warmed and pinned at /var/lib/arcade/env with this false
      # (hub-status: staged g1 / applied g1). The switch carrying this line
      # restarted both game units into `flox activate -d ... -g 1`. Back to
      # false is the rollback: the placeholder ExecStart at the next switch
      # and the checkout stays.
      enable = true;
      source = {
        kind = "floxhub";
        env = "imkarrer/arcade";
      };
      # Provenance only for this kind (schema.nix): the tree whose CI pushes
      # the generation, so hub-status can hold its origin HEAD against the
      # staged record's rev.
      tree = "home-arcade";
      # dir: derived to /var/lib/arcade/env (no state.dirs on the tenant;
      # homelab.host.paths.state/<tenant>/env). Inside the tenant's 0700
      # home, owned by arcade, as the pull unit creates it.
      units."arcade-freeciv.service" = {
        description = "Arcade Freeciv dedicated server (LAN only)";
        workingDirectory = "${state}/freeciv";
        command = [
          "freeciv-server"
          "--bind"
          hub.lanAddress
          "--port"
          (toString hub.freeciv.port)
          "--saves"
          "${state}/freeciv"
          "--log"
          "${state}/freeciv/server.log"
        ];
      };
      units."arcade-mindustry.service" = {
        description = "Arcade Mindustry dedicated server (LAN only)";
        workingDirectory = "${state}/mindustry";
        command = [ "mindustry-server" ];
        environment.JAVA_TOOL_OPTIONS = "-Xms256M -Xmx1G";
        # The module's three printf lines, verbatim, from the same options;
        # systemd appends each StandardInputText= line to the buffer with a
        # newline, which is what the module's `printf '%s\n'` produced.
        stdin = [
          "config name Arcade"
          "config port ${toString hub.mindustry.port}"
          "host ${hub.mindustry.map} ${hub.mindustry.mode}"
        ];
      };
    };

  # ---------------------------------------------------------------------------
  # Tier shares, rebalanced to point this machine at the model server.
  #
  # The defaults in modules/tenant/resources.nix (critical 0.35/0.50,
  # interactive 0.15/0.20, background 0.30/0.25, batch 0.10/0.05) were written
  # before ac-box had an LLM tenant, and they cap agent-hub at 75 GiB of a
  # 251 GiB machine. Measured on the box 8 Sep 2026 before changing anything:
  # 4 GiB of 251 in use, load average 0.00, and all thirteen containers
  # together at 275 MiB. There is nothing to reclaim from the other tenants --
  # the tier table was the only thing standing between the LLM and the box.
  #
  # Every value here is an override of a mkDefault in resources.nix, so no
  # mkForce is needed and the defaults stay intact for any other host.
  #
  # memoryShare must sum to <= 0.9 (resources.nix's budget assertion, which
  # runs whether or not enforce.slices is on). These sum to exactly 0.90.
  #
  # Two consequences worth stating out loud rather than discovering later:
  #
  #   1. assetto is never assigned a slice at all (tier = critical AND
  #      quiet.drainable = false), so its processes and containers run in
  #      system.slice, whose CPUWeight is unset -- i.e. 100. Giving background
  #      a CPUWeight of 700 therefore ranks the model server ABOVE the race
  #      servers under contention, not merely above the other tiers. That is
  #      the deliberate choice being made here. What protects racing is the
  #      fence, not the weight: cores 0-2 (plus siblings 28-30) are outside
  #      background's and batch's AllowedCPUs entirely, so system.slice has
  #      exclusive use of them no matter what the LLM is doing.
  #
  #   2. critical.cpuShare is not about how much CPU assetto gets -- its slice
  #      is empty. It is the input to reservedForCritical, i.e. how many
  #      physical cores the fence keeps for everything unsliced. Lowering it
  #      to 0.10 is what hands the model server the other 23 cores.
  homelab.tiers = {
    critical = {
      # 12.5 GiB. Measured usage of the whole racing stack: well under 1 GiB
      # (0.1 GiB current, 2.5 GiB peak since boot per memory.peak, 14 Sep
      # 2026). Was 0.10, then 0.05; each cut went to background so another
      # model could be resident. 5 GiB now.
      memoryShare = 0.02;
      cpuShare = 0.10; # -> 3 physical cores (0-2) reserved outside the fence.
    };
    interactive = {
      # 5 GiB for arcade + observability; 1.0 GiB current, 1.3 GiB peak
      # since boot. Was 0.05; the 0.03 went to background with the embedding
      # model (and klein 9B, resident until 20 Sep 2026).
      memoryShare = 0.02;
      cpuShare = 0.05;
    };
    background = {
      # ~203 GiB, sized to hold everything llama-swap.yaml's `matrix` (agent-hub;
      # the resident set: coder, instruct, embed, utility) keeps loaded at once, worst case:
      #     coder     80.5 GiB   measured, anonymous under -rtr, with KV
      #     instruct  80.4 GiB   measured (RSS, 14 Sep 2026)
      #     embed     ~2 GiB     0.6 GB of weights + KV for 8k, estimated
      #     utility   ~6 GiB     4.3 GB of weights + KV for 16k, estimated
      #     caches    21 GiB     --cache-ram 12288 + 8192 + 1024, all ceilings
      #     qdrant    ~0 GiB     an empty store; grows with the HNSW index
      #               ~190 GiB
      # Measured 20 Sep 2026 with both 80Bs warm and nothing else loaded:
      # AnonPages 161.9 GiB, MemAvailable 83.8 of 251.8 GiB. The ~13 GiB
      # this ceiling still has over the table is for the second-family
      # reviewer (homelab-e00) -- NOT enough for gpt-oss-120b (~63 GiB)
      # beside both 80Bs; that one replaces instruct or the tiers move.
      # Was 0.70 (~176 GiB) for the two Qwens alone. memoryShare is a
      # CEILING, not a reservation, so the unused part costs nothing at
      # runtime -- but it does consume the 0.9 budget, and the extra 0.11 is
      # the other three tiers' slack: 0.03 from critical, 0.03 from
      # interactive, 0.05 from batch. On batch: the earlier note here refused
      # to cut it while background's ceiling was partly unusable; now every
      # GiB of it is spoken for. batch's 25 GiB peak since boot equals its
      # ceiling -- page cache filling up to the limit, not evidence of
      # anonymous need; the agent's builds run make -j2 on two cores.
      #
      # Page cache counts against this ceiling too and is what gets reclaimed
      # first, so the cached copies of the resident GGUFs go -- the cost is
      # that a reload after an eviction (none in the table today: all three
      # are one set) reads from NVMe (~30 s) instead of from cache (~20 s).
      # Past reclaim there is no swap: the ceiling is enforced by an OOM
      # kill inside the slice, which llama-swap survives (it restarts the
      # backend), so the ~1 GiB of margin above is thin on purpose rather
      # than by accident.
      memoryShare = 0.81;
      cpuShare = 0.70; # CPUWeight 700, and cores 3-25 + siblings via the fence.
      # resources.nix defaults this to 10, which niced the inference server
      # down against everything else on the box. The tenant this tier exists
      # for is now the machine's primary workload.
      nice = 0;
    };
    batch = {
      # 12.5 GiB. Was the default 0.10 (~25 GiB), the figure ac-host's
      # docker-compose.buildkite.yml cites as the number to revisit if a
      # build OOMs -- revisit it there too if one does. The 0.05 went to
      # background (see the arithmetic there). CPU is where CI must yield,
      # hence the small cpuShare below.
      memoryShare = 0.05;
      # Sizes batch's OWN fence block (cores 26-27) as well as its weight.
      # Before the resources.nix fix, batch and background shared one
      # AllowedCPUs string, so a Buildkite Nix build ran on exactly the CPUs
      # the LLM was pinned to.
      cpuShare = 0.05;
    };
  };

  # ---------------------------------------------------------------------------
  # Identified as the one hard gap by docs/noop-reconciliation.md: nothing in
  # modules/platform/, host.nix or tenants.nix set this, and omitting it changes
  # the closure in a way that is tedious to trace back to its cause.
  # ---------------------------------------------------------------------------
  system.stateVersion = "26.05";
}
