# Generated by nixos-generate-config. Keep in sync with the box.
#
# Fetched read-only from ac-box:/var/lib/ac-host/src/hosts/ac-box/hardware-configuration.nix
# on 2026-09-07. Never invented, never hand-edited — re-fetch from the box if it
# drifts.
#
# This file is TRACKED in git, deliberately. It was gitignored at first, copying
# ac-host's convention; gate 1 showed that a flake copies only git-tracked files,
# so a build from github:imkarrer/homelab silently used the .example stub that
# will not boot a real machine. See .gitignore's NOTE and commit daac96f. Do not
# re-ignore it. Disk UUIDs are not secrets.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "ehci_pci"
    "mpt3sas"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5ae5d017-8b98-4e5b-b8c5-f5658120ac89";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F5F3-902E";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
