# Generated by nixos-generate-config on the Lenovo M920q itself, at install.
#
# Fetched read-only from arcade-box:/etc/nixos/hardware-configuration.nix on
# 2026-09-26 (as the installer's `arcade` login, over the operator's key).
# Never invented, never hand-edited: re-fetch from the box if it drifts.
#
# TRACKED in git, deliberately, like hosts/ac-box's: a flake copies only
# git-tracked files into the store, and hosts/arcade-box/configuration.nix
# throws rather than substitute a stub. Disk UUIDs are not secrets.
#
# Surveyed the same day: nvme0n1 953.9G -- p1 512M vfat /boot (1ACA-EF7F),
# p2 953.4G ext4 / (4b99b772-...); no swap; UEFI (AMI 5.13), systemd-boot,
# Secure Boot off, TPM2 present. i7-8700T, 6 cores / 12 threads, 31 GiB.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4b99b772-0e0c-4ae1-975a-5f689b62a517";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1ACA-EF7F";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
