"""boxctl -- read-only inspector for the ac-box homelab tenant contract.

HARD GUARANTEE: boxctl never applies a configuration, restarts a unit, or
otherwise changes ac-box's running state. There is no subcommand and no flag
that invokes `switch-to-configuration switch`, `switch-to-configuration
boot`, `switch-to-configuration test`, or any `nixos-rebuild` action other
than a read-only build of the closure. The only activation-related
subprocess boxctl ever runs is `switch-to-configuration dry-activate` --
NixOS's own dry-run mode, whose entire purpose is to report what WOULD
happen without doing it -- and that literal action name is hardcoded, not
derived from user input. Applying a plan and running it in the maintenance
window is a human action taken outside this tool.

boxctl reads /etc/homelab/tenants.json, generated by
modules/tenant/quiet.nix from the homelab.tenants.* contract
(modules/tenant/schema.nix). It never reads or writes anything else on a
live box.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Optional

DEFAULT_TENANTS_FILE = "/etc/homelab/tenants.json"

# hosts/ac-box/host.nix: homelab.host.maintenance.window. quiet.nix
# deliberately does not embed this in tenants.json -- it's an L0 (host) fact,
# not part of the tenant schema (README.md: "L1 knows only the schema") --
# so boxctl carries its own default and lets a human override it with
# --maintenance-window if the host fact ever changes.
DEFAULT_MAINTENANCE_WINDOW = "03:00"

# Restarting docker.service takes every container on the box down with it.
# ac-host-static.service's activation script does `docker rm -f` on the AC
# race containers (ac-box:/var/lib/ac-host/src) -- restarting or stopping it
# destroys whatever race is running. Both are always worth a loud, separate
# warning regardless of which tenant "owns" them.
DANGER_UNITS = frozenset({"docker.service", "ac-host-static.service"})

# Wording is pinned to switch-to-configuration-ng's src/main.rs (the sole
# implementation shipped in nixpkgs as of nixos-26.05 -- the old Perl
# switch-to-configuration script has been removed from the tree). These
# lines are written to stderr; boxctl doesn't care which stream you
# captured, only line content.
_UNIT_LIST_PATTERNS = [
    ("stop", re.compile(r"^would stop the following units:\s*(.+)$")),
    ("skip", re.compile(r"^would NOT stop the following changed units:\s*(.+)$")),
    ("reload", re.compile(r"^would reload the following units:\s*(.+)$")),
    ("restart", re.compile(r"^would restart the following units:\s*(.+)$")),
    ("start", re.compile(r"^would start the following units:\s*(.+)$")),
]
_RESTART_SYSTEMD_RE = re.compile(r"^would restart systemd$")


def die(message: str) -> None:
    print(f"boxctl: error: {message}", file=sys.stderr)
    sys.exit(2)


def load_tenants(path: Path) -> list[dict[str, Any]]:
    try:
        data = json.loads(path.read_text())
    except FileNotFoundError:
        die(
            f"{path} not found. It is written by modules/tenant/quiet.nix "
            "-- rebuild the host, or pass --tenants-file for a local copy."
        )
    except json.JSONDecodeError as exc:
        die(f"{path} is not valid JSON: {exc}")
    return data["tenants"]


def unit_owner_map(tenants: list[dict[str, Any]]) -> dict[str, str]:
    owner: dict[str, str] = {}
    for tenant in tenants:
        for unit in tenant["units"]:
            owner[unit] = tenant["name"]
    return owner


def run_busy_check(cmd: str) -> str:
    """schema.nix: quiet.busyCheck -- "Command; exit 0 means BUSY."."""
    try:
        proc = subprocess.run(
            ["/bin/sh", "-c", cmd],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=30,
        )
    except Exception as exc:  # noqa: BLE001 -- reported to the operator, not swallowed
        return f"busyCheck error ({exc})"
    return "BUSY" if proc.returncode == 0 else "not busy right now"


def drain_status(quiet: dict[str, Any], *, run_checks: bool) -> str:
    """Distinguish 'not drainable in principle' (policy) from 'not busy
    right now' (a real-time busyCheck reading), per schema.nix's own
    framing of quiet.busyCheck. The policy answer (drainable) is what
    governs whether a maintenance window is required -- busyCheck is
    informational color for a human, it never overrides the policy.
    """
    if quiet["drainable"]:
        return "drainable"
    if quiet.get("busyCheck") and run_checks:
        return f"NOT drainable (policy) -- {run_busy_check(quiet['busyCheck'])}"
    if quiet.get("busyCheck"):
        return "NOT drainable (policy); has a busyCheck"
    return "NOT drainable (policy); no busyCheck configured"


def parse_dry_activate(text: str) -> dict[str, Any]:
    """Parse `switch-to-configuration dry-activate` output into unit sets.

    Returns a dict with keys "stop", "skip", "reload", "restart", "start"
    (each a list[str], in first-seen order, de-duplicated) and
    "restart_systemd" (bool).
    """
    buckets: dict[str, list[str]] = {key: [] for key, _ in _UNIT_LIST_PATTERNS}
    restart_systemd = False
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if _RESTART_SYSTEMD_RE.match(line):
            restart_systemd = True
            continue
        for key, pattern in _UNIT_LIST_PATTERNS:
            match = pattern.match(line)
            if match:
                units = [u.strip() for u in match.group(1).split(",") if u.strip()]
                for unit in units:
                    if unit not in buckets[key]:
                        buckets[key].append(unit)
                break
    return {**buckets, "restart_systemd": restart_systemd}


def render_table(headers: list[str], rows: list[list[str]]) -> str:
    widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row):
            widths[i] = max(widths[i], len(cell))
    lines = ["  ".join(h.ljust(widths[i]) for i, h in enumerate(headers))]
    lines.append("  ".join("-" * w for w in widths))
    for row in rows:
        lines.append("  ".join(cell.ljust(widths[i]) for i, cell in enumerate(row)))
    return "\n".join(lines)


def cmd_status(args: argparse.Namespace) -> int:
    tenants = load_tenants(Path(args.tenants_file))
    rows = []
    for tenant in sorted(tenants, key=lambda t: t["name"]):
        rows.append(
            [
                tenant["name"],
                tenant["tier"],
                ", ".join(tenant["units"]) or "(none)",
                drain_status(tenant["quiet"], run_checks=not args.no_busy_check),
            ]
        )
    print(render_table(["TENANT", "TIER", "UNITS", "DRAINABLE"], rows))
    return 0


def get_toplevel(args: argparse.Namespace) -> Optional[Path]:
    if args.toplevel:
        return Path(args.toplevel)
    if args.flake_attr:
        # Read-only: `nix build` only realises a derivation in the Nix
        # store. It does not activate, switch, or touch systemd.
        proc = subprocess.run(
            [
                "nix",
                "--extra-experimental-features",
                "nix-command flakes",
                "build",
                "--no-link",
                "--print-out-paths",
                args.flake_attr,
            ],
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            die(f"`nix build {args.flake_attr}` failed:\n{proc.stderr}")
        out = proc.stdout.strip().splitlines()
        if not out:
            die(f"`nix build {args.flake_attr}` produced no output path")
        return Path(out[0])
    return None


def get_dry_activate_text(args: argparse.Namespace, toplevel: Optional[Path]) -> str:
    if args.dry_activate_output:
        return Path(args.dry_activate_output).read_text()
    if toplevel is None:
        die(
            "plan needs one of --toplevel, --flake-attr, or "
            "--dry-activate-output to know what to report on"
        )
    binary = toplevel / "bin" / "switch-to-configuration"
    if not binary.exists():
        die(f"{binary} does not exist -- is {toplevel} a system toplevel?")
    # This is the ONLY place boxctl ever runs switch-to-configuration, and
    # "dry-activate" is a literal, not a variable: no flag, env var, or
    # argument can turn this into switch/boot/test.
    proc = subprocess.run(
        [str(binary), "dry-activate"],
        capture_output=True,
        text=True,
    )
    # dry-activate exits 0 even when it reports changes; a non-zero exit
    # means the dry run itself failed to reason about the closure.
    if proc.returncode != 0:
        die(
            f"`switch-to-configuration dry-activate` exited {proc.returncode}:\n"
            f"{proc.stderr}"
        )
    return proc.stderr + proc.stdout


def cmd_plan(args: argparse.Namespace) -> int:
    tenants = load_tenants(Path(args.tenants_file))
    owner = unit_owner_map(tenants)
    by_name = {t["name"]: t for t in tenants}

    toplevel = get_toplevel(args)
    parsed = parse_dry_activate(get_dry_activate_text(args, toplevel))

    touched = set(parsed["stop"]) | set(parsed["restart"]) | set(parsed["reload"])
    danger = sorted(touched & DANGER_UNITS)

    # switch-to-configuration doesn't always say "would restart the following
    # units" for a bounced unit -- it sometimes reports the same unit in both
    # "would stop" and "would start" instead (seen live on the phase 6 plan,
    # with prometheus.service and grafana.service). Either shape is a
    # restart, not a stop plus an unrelated new start: a unit in this
    # intersection must never get labeled "(newly-started units, not
    # disruptive)" below, which undersells exactly the disruption (a scrape
    # gap, a dashboard blink) an operator most needs to see.
    bounced = set(parsed["stop"]) & set(parsed["start"])
    all_restarts = sorted(set(parsed["restart"]) | bounced)
    new_starts = [u for u in parsed["start"] if u not in bounced]

    print("would stop:   ", ", ".join(parsed["stop"]) or "(none)")
    print("would reload: ", ", ".join(parsed["reload"]) or "(none)")
    print("would restart:", ", ".join(all_restarts) or "(none)")
    if new_starts:
        print("would start:  ", ", ".join(new_starts), "(newly-started units, not disruptive)")
    if parsed["restart_systemd"]:
        print(
            "WARNING: systemd itself would re-exec ('would restart systemd') "
            "-- treat every unit on the box as potentially affected."
        )
    print()

    must_wait = False

    if danger:
        must_wait = True
        print(f"DANGER: dry-activate would touch: {', '.join(danger)}")
        if "ac-host-static.service" in danger:
            print(
                "        ac-host-static.service's activation script runs "
                "`docker rm -f` on the race containers -- this WILL destroy "
                "any race in progress."
            )
        if "docker.service" in danger:
            print(
                "        docker.service restarting takes every container on "
                "the box down with it (assetto, arcade, agent-hub, ci)."
            )
        print()

    affected: dict[str, set[str]] = {}
    unowned: list[str] = []
    for unit in sorted(touched):
        name = owner.get(unit)
        if name is None:
            unowned.append(unit)
        else:
            affected.setdefault(name, set()).add(unit)

    print("affected tenants:")
    if not affected:
        print("  (none of the touched units are owned by a declared tenant)")
    for name in sorted(affected):
        tenant = by_name[name]
        status = drain_status(tenant["quiet"], run_checks=not args.no_busy_check)
        if not tenant["quiet"]["drainable"]:
            must_wait = True
        units = ", ".join(sorted(affected[name]))
        print(f"  {name:<14} tier={tenant['tier']:<12} units=[{units}]  {status}")

    if unowned:
        print()
        print("units touched but not owned by any declared tenant:")
        print(f"  {', '.join(unowned)}")

    print()
    if must_wait:
        print(
            f"DECISION: cannot apply now -- wait for "
            f"homelab.host.maintenance.window ({args.maintenance_window})."
        )
    else:
        print("DECISION: no affected tenant requires a maintenance window.")
    print(
        "boxctl does not apply plans. Applying (switch-to-configuration "
        "switch / nixos-rebuild switch) is a human action, taken separately."
    )
    return 1 if must_wait else 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="boxctl",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command", required=True)

    status = sub.add_parser(
        "status",
        help="list tenants, tiers, units, and whether each is currently drainable",
    )
    status.add_argument("--tenants-file", default=DEFAULT_TENANTS_FILE)
    status.add_argument(
        "--no-busy-check",
        action="store_true",
        help="skip running busyCheck commands; report policy drainability only",
    )
    status.set_defaults(func=cmd_status)

    plan = sub.add_parser(
        "plan",
        help=(
            "build the host closure, run switch-to-configuration dry-activate "
            "(read-only), and report which tenants would be affected"
        ),
    )
    plan.add_argument("--tenants-file", default=DEFAULT_TENANTS_FILE)
    plan.add_argument(
        "--toplevel",
        help="path to an already-built system toplevel derivation "
        "(skips building; still never switches)",
    )
    plan.add_argument(
        "--flake-attr",
        help="flake installable to `nix build` (read-only) for the toplevel, "
        "e.g. .#nixosConfigurations.ac-box.config.system.build.toplevel",
    )
    plan.add_argument(
        "--dry-activate-output",
        help="path to a file containing previously-captured "
        "`switch-to-configuration dry-activate` output, instead of running it now "
        "(this is how boxctl's parser is tested, and how you can plan from a "
        "sample captured elsewhere without boxctl touching a box's systemd itself)",
    )
    plan.add_argument(
        "--maintenance-window",
        default=DEFAULT_MAINTENANCE_WINDOW,
        help=f"reported in the decision line only (default: {DEFAULT_MAINTENANCE_WINDOW}, "
        "matching hosts/ac-box/host.nix)",
    )
    plan.add_argument(
        "--no-busy-check",
        action="store_true",
        help="skip running busyCheck commands; report policy drainability only",
    )
    plan.set_defaults(func=cmd_plan)

    return parser


def main(argv: Optional[list[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
